export const ON_AUTH_INIT = 'ON_AUTH_INIT';
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const ON_AUTH = "ON_AUTH";
export const ON_REGISTER = "ON_REGISTER";
export const ON_REGISTRATION_FAILED = 'ON_REGISTRATION_FAILED';

export const PREPARE_CALLER = 'PREPARE_CALLER';
export const CALL_INIT = 'CALL_INIT';
export const CALL_ACCEPTED = 'CALL_ACCEPTED';
export const CALL_REJECTED = 'CALL_REJECTED';
export const ON_TRACK = 'ON_TRACK';
export const ON_LOCAL_STREAM = 'ON_LOCAL_STREAM';
export const ON_INCOMING_CALL = 'ON_INCOMING_CALL';
export const END_CALL = 'END_CALL';
export const ON_ERROR = 'ON_ERROR';

export const CHAT_INIT_SUCCESS = 'CHAT_INIT_SUCCESS';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const ON_NEW_MESSAGE = 'ON_NEW_MESSAGE';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILED = 'CREATE_GROUP_FAILED';
export const START_NEW_CHAT_SUCCESS = 'START_NEW_CHAT_SUCCESS';
export const START_NEW_CHAT_FAILED = 'START_NEW_CHAT_FAILED';
export const DELETE_CHAT = 'DELETE_CHAT';
export const JOIN_ROOM = 'JOIN_ROOM';
export const SUBSCRIPTIONSUCCESSFUL = 'SUBSCRIPTIONSUCCESSFUL';